export const KEYWORD_LIBRARY = Object.freeze({
  "摧毁": "将指定卡牌从本局永久牌组中移除；本轮之后也不会再次抽到。",
  "相邻": "读取初始牌序中紧挨本牌的前一张、后一张或两侧卡牌。",
  "成长": "永久提高这张实体卡牌写明的吃分或弃分；重洗与下一轮都会保留。",
  "生成": "向永久牌组加入一张新卡；达到牌组或该效果的生成上限时不会加入。",
  "重洗": "将本轮已处理且仍在永久牌组中的牌重新洗回牌堆。",
  "净化": "只将低于卡牌原值的红色吃点或弃点恢复到原值；绿色成长不会被移除。",
  "追溯": "读取本轮此前已经完成的行动或得分，不会再次触发那些卡牌。",
  "蓄势": "为之后符合条件的若干张牌保存加成；不符合条件的牌不会减少剩余次数。",
  "位置": "检查本牌在本轮行动顺序中的首位、次位、中位或末位。",
  "规模": "按永久牌组当前的张数、类别数量或不同卡名数量计算。",
  "复制": "复制指定分数数值，但不会复制被复制卡牌的效果。",
  "删牌": "获得删牌 token；只能在轮末选牌阶段打开永久牌组并消耗。",
  "储存": "把数值保存在这张实体牌上，跨轮保留，直到效果写明的结算方式将其清空。",
  "预判": "读取本轮尚未处理的牌，但不会改变它们的牌序或触发它们的效果。",
  "水果连击": "连续吃下水果会提高水果连击；吃下非水果或弃牌会中断连击。",
  "厌食": "这张快餐每次被吃后，吃分永久下降、弃分永久上升。",
  "留存": "弃掉这张甜点会永久提高它的吃分；达到门槛后吃下会爆发并摧毁自身。",
  "弱化": "这张生成牌无论被吃或弃，结算完效果后都会摧毁自身。",
  "休眠": "这张新购入牌在下一轮不会进入牌堆，再下一轮恢复正常。",
  "后置": "暂时不处理当前牌，将它移动到本次牌堆的最后；不结算吃弃，也不占用行动次数。每轮每张牌只能后置一次。",
  "机制": "直接改变牌序、计时、重洗或剩余牌面的基础规则。",
  "硬吃": "故意选择不符合食性的吃或弃；承担较低牌面，换取硬吃牌与道具的额外收益。",
});

const KIND_KEYWORDS = Object.freeze({
  bonus_if_previous: ["相邻"],
  bonus_if_next: ["相邻"],
  bonus_if_neighbors: ["相邻"],
  bonus_if_matching_neighbors: ["相邻"],
  bonus_if_exactly_one_neighbor: ["相邻"],
  bonus_if_neighbor_pair: ["相邻"],
  bonus_if_neighbor_types_different: ["相邻"],
  bonus_if_mixed_neighbors: ["相邻"],
  bonus_if_different_previous: ["相邻"],
  bonus_if_previous_score: ["相邻"],
  bonus_if_action_streak: ["追溯"],
  bonus_if_generated: ["生成"],
  bonus_from_next_base: ["相邻", "复制"],
  bonus_if_position_previous: ["位置", "相邻"],
  bonus_if_position: ["位置"],
  position_tradeoff: ["位置"],
  bonus_if_action_number: ["位置"],
  buff_next_action: ["蓄势"],
  buff_next_unique_types: ["蓄势"],
  grant_best_side_next: ["蓄势"],
  grant_opposite_side_next: ["蓄势"],
  wager_next_action: ["蓄势"],
  debuff_until_action: ["蓄势"],
  force_next_action_reward: ["蓄势"],
  debuff_next_action: ["蓄势"],
  clear_debuff: ["净化"],
  absorb_debuff: ["净化"],
  reset_buffs_bonus: ["净化"],
  permanent_growth_eat: ["成长"],
  permanent_growth_condition: ["成长"],
  consume_previous_card: ["摧毁", "成长", "相邻"],
  consume_next_card: ["摧毁", "成长", "相邻"],
  destroy_next_for_gold: ["摧毁", "相邻", "经济"],
  destroy_previous_generate: ["摧毁", "相邻", "生成"],
  destroy_previous_for_gold: ["摧毁", "相邻", "经济"],
  destroy_previous_discount: ["摧毁", "相邻", "经济"],
  destroy_self_buff: ["摧毁", "蓄势"],
  gold_economy: ["摧毁", "经济"],
  shop_free_reroll_destroy: ["摧毁", "经济"],
  gain_reshuffle_charge_destroy: ["摧毁", "重洗"],
  gain_reshuffle_charge: ["重洗"],
  generate_card: ["生成"],
  scale_by_deck: ["规模"],
  scale_by_unique_deck: ["规模"],
  bonus_if_type_majority: ["规模"],
  scale_by_remaining: ["预判"],
  scale_by_history: ["追溯"],
  scale_by_unique_history: ["追溯"],
  scale_by_negative_history: ["追溯"],
  streak_scale: ["追溯"],
  retro_multiplier_eaten_tag: ["追溯"],
  copy_previous_score: ["复制", "相邻"],
  copy_previous_score_capped: ["复制", "相邻"],
  shop_discount: ["经济"],
  dynamic_shop_discount: ["经济", "追溯"],
  gain_gold: ["经济"],
  gold_from_deck_type: ["经济", "规模"],
  gold_from_reserve: ["经济", "规模"],
  buff_remaining_type: ["蓄势"],
  gold_on_discard_count: ["经济", "追溯"],
  gold_from_history: ["经济", "追溯"],
  store_or_cashout: ["储存"],
  rabbit_formation: ["规模"],
  discard_all_remaining: ["追溯"],
  fruit_combo: ["水果连击"],
  fruit_combo_resume: ["水果连击"],
  fruit_combo_discard_shield: ["水果连击", "摧毁", "机制"],
  fruit_combo_forecast: ["水果连击", "预判"],
  reserve_growth: ["成长", "规模"],
  destroy_generate_many: ["摧毁", "生成"],
  anorexia: ["厌食", "成长"],
  early_time_bonus: ["机制"],
  fast_food_anorexia_or_positive_count: ["厌食", "成长", "规模"],
  scale_degraded_fast_food: ["厌食", "规模"],
  bonus_if_degraded_fast_food_history: ["厌食", "追溯"],
  retention: ["留存", "成长"],
  round_end_decay: ["成长"],
  transfer_dessert_growth: ["成长"],
  scale_by_reserve_type: ["规模", "预判"],
  forecast_tail_edibility: ["预判"],
  drink_consume: ["摧毁"],
  store_charges: ["储存"],
  speed_window_destroy: ["摧毁", "机制", "经济"],
  copy_last_fruit_destroy: ["复制", "生成", "弱化", "摧毁", "追溯"],
  discard_for_gold: ["经济"],
  generate_by_decay: ["生成", "成长", "摧毁", "弱化"],
  drain_random_to_self: ["成长"],
  drain_type_to_self: ["成长", "规模"],
  wrong_edibility_bonus: ["硬吃"],
  wrong_edibility_streak: ["硬吃", "追溯"],
  wrong_history_scale: ["硬吃", "追溯"],
  wrong_edibility_setup_destroy: ["硬吃", "蓄势", "摧毁"],
  generate_random: ["生成"],
  swap_remaining_sides: ["机制"],
  celestial_sun: ["重洗", "摧毁"],
  bonus_if_postponed: ["后置"],
  purify_one_if_postponed: ["后置", "净化"],
  fetch_reserve_animal: ["机制", "预判"],
  imprint_previous_score: ["复制", "成长", "追溯"],
  force_weakest_shop_type: ["经济", "规模"],
  prime_reverse_postpone: ["后置", "蓄势", "机制"],
  prime_postpone_score: ["后置", "蓄势"],
  pause_timer: ["机制"],
  gather_unresolved_type: ["机制"],
  recall_tail: ["机制"],
  destroy_neighbors: ["摧毁", "相邻"],
  nebula_wager: ["机制", "预判", "追溯"],
  scale_by_gold: ["经济", "规模"],
  scale_by_reserve_unique_types: ["规模", "预判"],
  prime_verdict: ["硬吃", "蓄势"],
  schedule_purify: ["净化", "蓄势"],
  layaway: ["经济", "蓄势", "休眠"],
  lock_next_stats: ["机制", "蓄势"],
  fruit_history_bonus: ["追溯"],
  bidirectional_anorexia: ["厌食", "成长", "经济"],
  anorexia_postpone_drain: ["厌食", "后置", "成长"],
  double_anorexia: ["厌食", "机制", "成长"],
  postpone_mark_all_trade: ["后置", "成长", "机制"],
  early_time_gold: ["经济", "机制"],
  bonus_if_degraded_history: ["追溯"],
  postpone_destroy_buff_next: ["后置", "摧毁", "成长", "相邻"],
  postpone_match_highest_eat: ["后置", "成长", "预判"],
  scale_by_pile_type: ["规模", "预判"],
  fruit_combo_unbreakable: ["水果连击", "摧毁", "机制"],
  postpone_decay_gold: ["后置", "成长", "经济"],
  slow_finish_gold_destroy: ["摧毁", "经济", "机制"],
  copy_pile_dessert_destroy: ["复制", "生成", "弱化", "摧毁", "预判"],
  drain_pile_edible_to_self: ["成长", "预判"],
  postpone_penalty_comeback: ["后置", "成长", "硬吃"],
  destroy_self_raise_rarity: ["摧毁", "经济"],
  postpone_buff_animal: ["后置", "成长", "预判"],
  discard_pay_for_reroll: ["经济"],
  postpone_mark_all_growth: ["后置", "成长", "机制"],
  delay_milestone_destroy: ["摧毁", "机制"],
  buff_marked_remaining: ["后置", "蓄势"],
  destroy_marked_remaining: ["后置", "摧毁"],
  postpone_nebula: ["后置", "机制", "追溯"],
  scale_by_pile_unique_types: ["规模", "预判"],
  scale_by_unique_deck_types: ["规模"],
  postpone_generate_edible: ["后置", "成长", "生成", "弱化"],
  prime_review: ["硬吃", "蓄势", "经济"],
  postpone_mark_all_wrong_eat: ["后置", "硬吃", "机制"],
  buff_two_marked: ["后置", "蓄势"],
  force_shop_price_four: ["经济"],
  eat_reroll_or_discard_delete: ["摧毁", "经济"],
  mark_all_protect_decrease: ["后置", "机制"],
  bank_interest: ["经济"],
  purify_deck: ["净化"],
  buff_deck_points: ["成长"],
  gain_delete_token_destroy: ["删牌", "摧毁"],
  choice_score_or_delete_token: ["删牌", "摧毁"],
  early_action_bonus: ["位置"],
  flat_action_bonus: [],
  postpone_decay_score: ["后置", "成长"],
  destroy_self_score: ["摧毁"],
});

const DESTROY_SYNONYMS = /永久销毁|永久吞掉|永久藏走|永久烹掉|永久清走|销毁|吞掉|藏走|烹掉|清走|消耗掉/g;

export function canonicalizeDescription(description = "") {
  return String(description).replace(DESTROY_SYNONYMS, "摧毁");
}

export function getEffectKeywords(effect) {
  if (!effect) return [];
  const derived = [
    effect.destroy_self ? "摧毁" : null,
    effect.condition_position ? "位置" : null,
    effect.requires_previous || effect.requires_next ? "相邻" : null,
  ].filter(Boolean);
  return [...new Set([...(KIND_KEYWORDS[effect.kind] ?? []), ...derived, ...(effect.keywords ?? [])])]
    .filter((keyword) => KEYWORD_LIBRARY[keyword]);
}

export function normalizeEffect(effect) {
  if (!effect) return null;
  const keywords = getEffectKeywords(effect);
  const description = canonicalizeDescription(effect.description);
  return {
    ...effect,
    keywords,
    description,
  };
}

export function stripKeywordTags(description = "") {
  return String(description).replace(/【[^】]+】\s*/g, "").trim();
}
